// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app;

  app = angular.module('kuew');

  app.filter('field', function(_) {
    return function(list, name) {
      return _.map(list, function(n) {
        return n[name];
      });
    };
  });

}).call(this);
