// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app;

  app = angular.module('kuew');

  app.filter('pluralize', function() {
    return function(value, count) {
      if (!angular.isDefined(count)) {
        count = 1;
      }
      if (count === 1) {
        return value;
      }
      if (value === 'person') {
        return 'people';
      } else if (value === 'foot') {
        return 'feet';
      } else if (value === 'tooth') {
        return 'teeth';
      } else if (value === 'roof') {
        return 'roofs';
      } else if (/y$/.test(value)) {
        return value.replace(/y$/, 'ies');
      } else if (/s$/.test(value)) {
        return value.replace(/s$/, 'ses');
      } else if (/sh$/.test(value)) {
        return value.replace(/sh$/, 'shes');
      } else if (/ch$/.test(value)) {
        return value.replace(/ch$/, 'ches');
      } else if (/ge$/.test(value)) {
        return value.replace(/ge$/, 'ges');
      } else if (/f[e]?$/.test(value)) {
        return value.replace(/f[e]?$/, 'ves');
      } else {
        return value + 's';
      }
    };
  });

}).call(this);
