// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app, e, elements, _i, _len,
    _this = this;

  elements = ["wizard", "step", "branch"];

  for (_i = 0, _len = elements.length; _i < _len; _i++) {
    e = elements[_i];
    document.createElement(e);
  }

  app = angular.module('kuew', ['ui.bootstrap', 'ngDragDrop']);

  app.factory('_', function() {
    return _this._;
  });

  app.factory('$', function() {
    return _this.jQuery;
  });

  app.factory('templatePath', function() {
    var path;
    path = location.pathname;
    if (path.substr(path.length - 1) !== '/') {
      path = path.replace(/\/[^\/]+$/, '/');
    }
    path += 'html-templates/';
    return function(partial) {
      return path + partial;
    };
  });

  this.angularScript = function(path, useMinified) {
    var extension, tag;
    extension = ".js";
    if (useMinified) {
      extension = ".min.js";
    }
    tag = "<script type=\"text/javascript\" " + ("src=\"js/lib/angular/" + path + extension + "\"></") + "script>";
    return document.write(tag);
  };

}).call(this);
