// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var $a, app;

  app = angular.module('kuew');

  $a = angular.element;

  app.directive('filteredList', function(_, $timeout, templatePath) {
    return {
      restrict: 'EA',
      replace: true,
      templateUrl: templatePath('components/filtered-list.html'),
      transclude: false,
      scope: {
        filteredList: '@',
        heading: '@',
        filterId: '@',
        filterScope: '@'
      },
      link: function($scope, element, attrs) {
        var elements, selector;
        selector = _.map(attrs.filteredList.split(' '), function(c) {
          return "" + attrs.filterScope + "." + c;
        });
        selector = selector.join(', ');
        elements = $a(selector);
        $scope.teamMembers = _.map(elements, function(el) {
          var e;
          e = $a(el);
          return {
            name: e.data('name'),
            email: e.data('email'),
            profileImage: e.data('profileimg'),
            role: e.data('role'),
            social: {
              twitter: e.data('twitter'),
              fb: e.data('fb')
            }
          };
        });
        return $timeout(function() {
          return element.find('.livicon').each(function() {
            $a(this).addLivicon().hide();
            return element.find('ul.deptList li').hover(function() {
              return $a(this).find(".livicon").fadeIn('fast');
            }, function() {
              return $a(this).find(".livicon").fadeOut('fast');
            });
          });
        }, 100);
      }
    };
  });

}).call(this);
