// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app;

  app = angular.module('kuew');

  app.directive('stepInput', function($injector) {
    return {
      require: '^multiStepInput',
      tranclude: true,
      replace: true,
      template: '<div></div>',
      scope: {
        inputType: '@type',
        name: '@',
        options: '='
      },
      link: function($scope, element, attr, controller) {
        var clazz, layout;
        clazz = new $injector.get("Kuew" + attr.type + "ActionItem");
        layout = {
          inputType: attr.type,
          name: attr.name,
          model: new clazz($scope, $scope.options)
        };
        controller.pushLayout(layout);
        return $scope.$on('event:itemIsValidChanged', function($event, item, value) {
          if (value === true) {
            return layout.model.finishEdit();
          }
        });
      }
    };
  });

}).call(this);
