// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app;

  app = angular.module('kuew');

  app.directive('userSkills', function(templatePath) {
    return {
      restrict: 'EA',
      templateUrl: templatePath('components/user-skills.html'),
      transclude: false,
      replace: true,
      link: function($scope, element, attrs) {
        $scope.skills = [];
        $scope.skillNames = ['HTML5', 'PHP', 'JQuery', 'Graphic Design', 'UI', 'Marketing', 'Market Research', 'Social Media', 'Social Media Marketing', 'Facebook Marketing', 'LinkedIn', 'Email Marketing', 'MySql', 'Kuew', 'Human Resources', 'Management '];
        return $scope.removeSkill = function(skill) {
          var idx;
          idx = $scope.skills.indexOf(skill);
          if (idx < 0) {
            return;
          }
          return $scope.skills.splice(idx, 1);
        };
      }
    };
  });

}).call(this);
