// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app;

  app = angular.module('kuew');

  app.factory('Action', function($rootScope) {
    var Action;
    return Action = (function() {
      function Action(parentScope) {
        if (angular.isDefined(parentScope)) {
          this.$scope = parentScope.$new();
        } else {
          this.$scope = $rootScope.$new();
        }
        this.$scope.steps = {};
      }

      Action.prototype.hasStep = function(name) {
        var key;
        return ((function() {
          var _results;
          _results = [];
          for (key in this.$scope.steps) {
            if (key === name) {
              _results.push(key);
            }
          }
          return _results;
        }).call(this)).length > 0;
      };

      Action.prototype.addStep = function(name) {
        return this.$scope.steps[name] = null;
      };

      Action.prototype.removeStep = function(name) {
        if (this.hasStep(name)) {
          return delete this.$scope.steps[name];
        }
      };

      Action.prototype.addOption = function(step, options) {};

      return Action;

    })();
  });

}).call(this);
