// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('kuew');

  app.factory('KuewTypeAheadActionItem', function(KuewActionItem, templatePath) {
    var KuewTypeAheadActionItem;
    return KuewTypeAheadActionItem = (function(_super) {
      __extends(KuewTypeAheadActionItem, _super);

      function KuewTypeAheadActionItem(scope, options) {
        KuewTypeAheadActionItem.__super__.constructor.call(this, scope, options);
      }

      KuewTypeAheadActionItem.prototype.templateUrl = templatePath('components/action-items/typeahead.html');

      KuewTypeAheadActionItem.prototype.validate = function() {
        return angular.isArray(this.options.typeahead) && this.options.typeahead.indexOf(this.value) >= 0;
      };

      return KuewTypeAheadActionItem;

    })(KuewActionItem);
  });

}).call(this);
