// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app;

  app = angular.module('kuew');

  app.factory('KuewActionItem', function($rootScope) {
    var KuewActionItem;
    return KuewActionItem = (function() {
      function KuewActionItem(scope, options) {
        var s,
          _this = this;
        s = angular.isDefined(scope) ? scope : $rootScope;
        this.scope = s.$new();
        this.scope.editing = true;
        this.scope.value = null;
        this.scope.options = options;
        this.scope.beginEdit = function() {
          return _this.beginEdit();
        };
        this.scope.finishEdit = function() {
          return _this.finishEdit();
        };
        Object.defineProperty(this, 'editing', {
          get: function() {
            return this.scope.editing;
          }
        });
        Object.defineProperty(this, 'value', {
          get: function() {
            return this.scope.value;
          }
        });
        Object.defineProperty(this, 'options', {
          get: function() {
            return this.scope.options;
          }
        });
      }

      KuewActionItem.prototype.beginEdit = function() {
        return this.scope.edit = true;
      };

      KuewActionItem.prototype.finishEdit = function() {
        return this.scope.edit = false;
      };

      KuewActionItem.prototype.isValid = function() {
        throw new Error("Not Implemented");
      };

      KuewActionItem.prototype.tamplateUrl = void 0;

      return KuewActionItem;

    })();
  });

}).call(this);
