// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('kuew');

  app.factory('KuewSimpleInputActionItem', function(KuewActionItem, templatePath) {
    var KuewSimpleInputActionItem;
    return KuewSimpleInputActionItem = (function(_super) {
      __extends(KuewSimpleInputActionItem, _super);

      function KuewSimpleInputActionItem(scope, options) {
        KuewSimpleInputActionItem.__super__.constructor.call(this, scope, options);
        this.setDefaultOption('inputType', 'text');
      }

      KuewSimpleInputActionItem.prototype.templateUrl = templatePath('components/action-items/simple.html');

      KuewSimpleInputActionItem.prototype.validate = function() {
        var valid;
        valid = true;
        if (angular.isFunction(this.options.validate)) {
          valid = valid && this.options.validate(this);
        }
        return valid;
      };

      return KuewSimpleInputActionItem;

    })(KuewActionItem);
  });

}).call(this);
